spring:
  application:
    name: notification-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_menu
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: f879e546a79d80
    password: 97b60a852fafba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: 8081
