spring:
  application:
    name: notification-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_menu
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 50
      fetch-min-size: 1024
      fetch-max-wait: 500
    listener:
      ack-mode: batch
      concurrency: 3

server:
  port: 8081
